spring:
  datasource:
    url: jdbc:mysql://192.168.10.12:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: yanfa
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver