spring:
  datasource:
    url: jdbc:mysql://192.168.10.12:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: yanfa
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#  jpa: 
#    database: mysql
#    hibernate.ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl